[package]
name = "ServersideLogger"
version = "0.1.0"
edition = "2021"
description = "Console logger to better output the current status of execution, etc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
