# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart-dev

on:
  pull_request:
    branches: [ "Dev", "Staging/Testing", "Prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with: 
          channel: beta

      - name: Install dependencies
        run: flutter pub get -C ./FE/

      - name: Analyze project source
        run: flutter analyze ./FE/ --no-pub --no-fatal-infos --no-fatal-warnings

