name: Rust-Prod

on:
  push:
    branches: [ "Prod" ]
  pull_request:
    branches: [ "Prod" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: change-directory
      run: cd BE/
    - name: Lint
      run: cargo check
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --workspace --verbose
      
