name: Rust-Dev

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo +nightly -Z -C BE/ check
