name: Rust-Prod

on:
  pull_request:
    branches: [ "Staging/Testing", "Prod" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build project
      run: cargo build --bin --manifest-path=./BE/Cargo.toml
      
