name: Staging-Testing

on:
  push:
    branches: [ "Staging/Testing" ]
  pull_request:
    branches: [ "Staging/Testing" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo check
    - name: Build
      run: cargo build --verbose
