name: Rust-lint

on:
  pull_request:
    branches: [ "Dev", "Staging/Testing", "Prod" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cd BE/ && cargo check
